<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "cySendMails"
 *
 * Auto generated by Extension Builder 2020-03-18
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Send a mail to other frontend user or frontend user groups.',
    'description' => 'LLL:EXT:cy_send_mails/Resources/Private/Language/locallang_be_messageForm.xlf:plugin.description',
    'category' => 'plugin',
    'author' => 'C. Gogolin',
    'author_email' => 'service@cylancer.net',
    'state' => 'beta',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 1,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '11.5.12-11.5.99',
            'bootstrap_package' => '11.0.2-12.9.99'
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];


